language: python

dist: xenial
sudo: true

cache:
  directories:
    - $HOME/env

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7

before_install:
    - bash .travis_dependencies.sh
    - export PATH="$HOME/env/miniconda$TRAVIS_PYTHON_VERSION/bin:$PATH";
    - hash -r
    - source activate test-environment
    - bash prepare_tests.sh

install:
    - pip install -U pip wheel
    - pip install -e .[tests,docs]

script:
    - py.test -v --cov-report= --cov=musdb tests/
    - python setup.py build_sphinx
    - python setup.py egg_info -b.dev sdist --formats gztar

after_success:
    - coveralls
