# global dataset samplerate
sample_rate: 44100.0

# Define the Input sources for each track
sources:
    degraded_instrument_track: degraded_instrument_track.wav
    degraded_backing_track: degraded_backing_track.wav

# Additionally provide the artistic mix
mixture:
    degraded_audio_mix.wav

stem_ids:
    mixture: 0
    degraded_instrument_track: 1
    degraded_backing_track: 2

# These are the gains to be used
targets:
    degraded_instrument_track: 
        degraded_instrument_track: 1
    degraded_backing_track:
        degraded_backing_track: 1

# Since this is meant to be used for testing. I deleted the parts related to the linear mixes and the validation tracks.
